def jsonify:if type == "null" then null else . | @json end;
map([
  .systeemId?,
  .naam,
  .partij,
  (.types?|.[] |if type == "array" then "{"+(join(","))+"}" else . end),
  (.categorie?|.catnr),
  .citeertitel?,
  .aangeslotenBijPensioenfonds?,
  .aantalInwoners?,
  .aantekening?,
  .afkorting?,
  (.afwijkendeBepaling?|jsonify),
  (.archiefzorgdrager?|.[0].systeemId),
  (.beleidsterreinen?|jsonify),
  .beschrijving?,
  .bevoegdheden?,
  (.bevoegdheidsverkrijgingen?|if type == "array" then "{"+(.[] |join(","))+"}" else . end),
  (.bronhouder?|.[0].systeemId),
  (.classificaties?|jsonify),
  (.contact?|jsonify),
  .datumInwerkingtreding?,
  .datumOpheffing?,
  .doel?,
  .eindDatum?,
  .geldendeCAO?,
  .ictuCode?,
  .installatie?,
  (.instellingsbesluiten?|if type != "null" then map(gsub("'";"''")|@json)|"{"+join(",")+"}" else . end),
  .inwonersPerKm2?,
  .kaderwetZboVanToepassing?,
  .kvkNummer?,
  (.laatsteEvaluatie?|jsonify),
  .omvatPlaats?,
  .oppervlakte?,
  .organisatiecode?,
  .partijFunctie?,
  (.personeelsomvang?|jsonify),
  .provincieAfkorting?,
  .rechtsvorm?,
  .registratiehouder?,
  (.relatieMetMinisterie?|.systeemId),
  (.resourceIdentifiers?|jsonify),
  (.samenwerkingsvorm?|.afkorting?),
  .standplaats?,
  .startDatum?,
  .subnaam?,
  .subtype?,
  .taalcode?,
  .takenEnBevoegdheden?,
  .titel?,
  .totaalZetels?,
  (.wettelijkeVoorschriften?|jsonify),
  (.zetels|jsonify)
]|walk(if type == "null" then "<<NULL>>" else . end))[]|@tsv|gsub("<<NULL>>";"\\N")
